#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: 2026 David González López-Tercero <davidglt@dragonit.es>
# SPDX-License-Identifier: GPL-3.0-or-later

r"""
SharpCap Focus Sequencer — On-demand thermal focus compensator.

Reads the regression model and last autofocus reference produced by
sharpcap-focus-temperature (sharpcap_focus_state.json), queries the
current temperature from the ZWO EAF external sensor via ASCOM, and
moves the focuser to the thermally compensated position.

Formula
-------
    focus_target = focus_ref + TCF * (T_current - T_ref)

Where:
    focus_ref  = focuser position at the reference autofocus point
    T_ref      = temperature at the reference autofocus point
    T_current  = current temperature read from the EAF sensor
    TCF        = temperature compensation factor (steps / °C)

Backlash compensation
---------------------
    To eliminate backlash, the focuser always arrives at the target
    from below (increasing step numbers = outward direction on C8 + F/6.3).
    If the target is below the current position, the script first moves
    to (target - backlash_steps) and then moves up to the target.
    The backlash value is configurable via --backlash (default: 500 steps).
    Set to 0 to disable backlash compensation entirely.

Minimum correction threshold
-----------------------------
    The --min-correction threshold applies ONLY when a backlash overshoot
    would be needed (target < current_position). In that case, a small
    correction is not worth the cost of a double move (overshoot + return).
    When no backlash is needed (target >= current_position), the script
    always moves, even if the correction is tiny, to keep the focus
    continuously well-corrected without accumulating drift.
    With TCF = -61.59 steps/°C, 50 steps corresponds to ~0.81 °C.
    Set to 0 to always move regardless of correction size or direction.

Busy detection
--------------
    If the focuser is already moving when the script connects (e.g. SharpCap
    is running an autofocus), the script aborts immediately and exits cleanly.
    The PERIODIC ThermalCorrection will retry in 7 minutes.

ASCOM access
------------
    ASCOM Device Hub is required to allow simultaneous access from
    SharpCap and this script. Configure Device Hub to proxy
    ASCOM.EAF_2.Focuser (main tube: C8 + ASI2600MC Pro, ~25 000 steps)
    and point both clients to ASCOM.DeviceHub.Focuser.

    Direct ProgIDs (ZWO EAF driver, single-client only):
        ASCOM.EAF.Focuser    -> first EAF  (guide tube: 50ED + ASI224MC,  ~335 000 steps)
        ASCOM.EAF_2.Focuser  -> second EAF (main tube:  C8  + ASI2600MC Pro, ~25 000 steps)

State JSON lookup
-----------------
    The script looks for sharpcap_focus_state.json in this order:
        1. Path supplied via --state-json (if given)
        2. Same directory as this script
        3. Sibling repository: ..\sharpcap-focus-temperature\

    The state JSON is generated by sharpcap-focus-temperature and must
    NOT be copied into this repository; always use the original output
    from the producer repository (single source of truth).

Dry-run mode
------------
    In --dry-run mode the script connects to the ASCOM driver to read the
    real focuser position and temperature, but does NOT move the focuser
    and does NOT update the state JSON. This gives an accurate simulation
    of what the live run would do. Supply --temp to override the temperature
    read from the driver (useful when the EAF sensor is not connected).

Logging
-------
    Each run appends to logs/YYYYMMDD_focus_sequencer.log (one file per day).
    The logs/ directory is created automatically if it does not exist.
    Log files are not committed to the repository (.gitignore).

    Every execution produces exactly one START line and one END line,
    with zero or more INFO/SKIP/ERROR lines in between.

    Log line format:
        YYYY-MM-DD HH:MM:SS | LEVEL | <message>

    Levels used:
        START  — beginning of each execution; reference data from state JSON
                 (last_focus and last_T are the values applied in the previous
                 run, not an estimate of the current state)
        INFO   — successful correction with full details, or no move needed
        SKIP   — correction skipped (focuser busy or below min-correction)
        ERROR  — unexpected error (ASCOM failure, move timeout, sensor error)
        DRY    — dry-run execution (no move performed)
        END    — end of each execution; always written regardless of outcome
                 pos=N/A when focuser could not be connected

    Example session (successful correction):
        2026-08-25 23:14:00 | START | ref=2026-08-25T21:30:00 | focus_ref=24831 | T_ref=18.50°C | TCF=-61.59 | last_focus=24831 | last_T=18.50°C | backlash=500 | min_correction=50
        2026-08-25 23:14:02 | INFO  | T=17.20°C | ΔT=-1.30°C | TCF=-61.59 | pos=24831 | correction=+80 | backlash=False | final=24911
        2026-08-25 23:14:02 | END   | pos=24911 | reason=ok

    Example session (focuser busy):
        2026-08-25 23:21:00 | START | ...
        2026-08-25 23:21:01 | SKIP  | Focuser busy (IsMoving=True) — skipping this cycle, retry in 7 min
        2026-08-25 23:21:01 | END   | pos=24911 | reason=busy

    Example session (below min-correction):
        2026-08-25 23:28:00 | START | ...
        2026-08-25 23:28:02 | SKIP  | T=17.10°C | ΔT=-1.40°C | correction=+12 | below min_correction=50 (backlash direction) — skipped
        2026-08-25 23:28:02 | END   | pos=24911 | reason=min_correction

    Example session (ASCOM connection failure):
        2026-08-25 23:35:00 | START | ...
        2026-08-25 23:35:01 | ERROR | ASCOM connection failed: No such device 'ASCOM.DeviceHub.Focuser'
        2026-08-25 23:35:01 | END   | pos=N/A | reason=error

    Example session (move timeout):
        2026-08-25 23:42:00 | START | ...
        2026-08-25 23:43:02 | ERROR | T=17.00°C | pos=24911 | target=24991 | move failed: Focuser did not reach position 24991 within 60s
        2026-08-25 23:43:02 | END   | pos=24911 | reason=error

    Example session (temperature sensor disconnected):
        2026-08-25 23:49:00 | START | ...
        2026-08-25 23:49:01 | ERROR | Could not read temperature: Temperature returned None — check EAF sensor
        2026-08-25 23:49:01 | END   | pos=24911 | reason=error

Usage
-----
    python focus_sequencer.py
    python focus_sequencer.py --state-json path/to/sharpcap_focus_state.json
    python focus_sequencer.py --ascom-id "ASCOM.EAF_2.Focuser"
    python focus_sequencer.py --dry-run
    python focus_sequencer.py --dry-run --temp 18.5
    python focus_sequencer.py --backlash 500
    python focus_sequencer.py --backlash 0        # disable backlash compensation
    python focus_sequencer.py --min-correction 50 # backlash overshoot threshold
    python focus_sequencer.py --min-correction 0  # always move regardless of direction

Author
------
David González López-Tercero

Contact
-------
Email: davidglt@dragonit.es
Website: https://dragonit.es

Date
----
2026-08-25

License
-------
GPL-3.0-or-later
"""

import argparse
import json
import logging
import sys
import time
from datetime import datetime
from pathlib import Path

DEG_C = "\u00B0C"
STATE_JSON_FILENAME = "sharpcap_focus_state.json"
DEFAULT_ASCOM_ID = "ASCOM.DeviceHub.Focuser"
DEFAULT_BACKLASH_STEPS = 500
DEFAULT_MIN_CORRECTION = 50
MOVE_TIMEOUT_S = 60
MOVE_POLL_INTERVAL_S = 0.5

_STATE_JSON_CANDIDATES = [
    Path(__file__).resolve().parent / STATE_JSON_FILENAME,
    Path(__file__).resolve().parent.parent / "sharpcap-focus-temperature" / STATE_JSON_FILENAME,
]


# ---------------------------------------------------------------------------
# Logging setup
# ---------------------------------------------------------------------------

def setup_logging() -> logging.Logger:
    """Configure and return the module logger.

    Appends to logs/YYYYMMDD_focus_sequencer.log (created if absent).
    Also streams to stdout so SharpCap's RUN output is visible.
    """
    log_dir = Path(__file__).resolve().parent / "logs"
    log_dir.mkdir(exist_ok=True)

    log_filename = log_dir / f"{datetime.now().strftime('%Y%m%d')}_focus_sequencer.log"

    fmt = "%(asctime)s | %(levelname)-5s | %(message)s"
    datefmt = "%Y-%m-%d %H:%M:%S"

    logger = logging.getLogger("focus_sequencer")
    logger.setLevel(logging.DEBUG)

    fh = logging.FileHandler(log_filename, mode="a", encoding="utf-8")
    fh.setLevel(logging.DEBUG)
    fh.setFormatter(logging.Formatter(fmt, datefmt=datefmt))
    logger.addHandler(fh)

    ch = logging.StreamHandler(sys.stdout)
    ch.setLevel(logging.DEBUG)
    ch.setFormatter(logging.Formatter(fmt, datefmt=datefmt))
    logger.addHandler(ch)

    return logger


# Custom level names so the log file shows fixed-width labels
logging.addLevelName(logging.INFO,    "INFO ")
logging.addLevelName(logging.WARNING, "SKIP ")
logging.addLevelName(logging.ERROR,   "ERROR")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def resolve_state_json(cli_path: str | None) -> Path:
    if cli_path is not None:
        p = Path(cli_path).resolve()
        if not p.exists():
            raise FileNotFoundError(f"--state-json path not found: {p}")
        return p
    for candidate in _STATE_JSON_CANDIDATES:
        if candidate.exists():
            return candidate
    searched = "\n  ".join(str(c) for c in _STATE_JSON_CANDIDATES)
    raise FileNotFoundError(
        f"sharpcap_focus_state.json not found in any of:\n  {searched}\n"
        "Run sharpcap_focuser.py (sharpcap-focus-temperature) first to generate it."
    )


def parse_arguments():
    parser = argparse.ArgumentParser(
        description=(
            "On-demand thermal focus compensator for ZWO EAF via ASCOM. "
            "Reads the model from sharpcap_focus_state.json and moves the "
            "focuser to the thermally corrected position."
        )
    )
    parser.add_argument("--state-json", default=None)
    parser.add_argument("--ascom-id", default=DEFAULT_ASCOM_ID)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--temp", type=float, default=None, metavar="DEGREES")
    parser.add_argument("--backlash", type=int, default=DEFAULT_BACKLASH_STEPS, metavar="STEPS")
    parser.add_argument("--min-correction", type=int, default=DEFAULT_MIN_CORRECTION, metavar="STEPS")
    parser.add_argument("--move-timeout", type=float, default=MOVE_TIMEOUT_S)
    return parser.parse_args()


def load_state(state_json_path: Path) -> dict:
    with state_json_path.open("r", encoding="utf-8") as handle:
        state = json.load(handle)
    required = ["focus_ref", "temp_ref", "model_tcf", "last_temp_applied", "last_focus_applied"]
    missing = [k for k in required if k not in state]
    if missing:
        raise ValueError(f"State JSON is missing required fields: {missing}")
    if state["model_tcf"] is None:
        raise ValueError("model_tcf is null in the state JSON.")
    return state


def connect_focuser(ascom_id: str):
    try:
        import win32com.client
    except ImportError:
        raise ImportError("pywin32 is required. Install with: pip install pywin32")
    focuser = win32com.client.Dispatch(ascom_id)
    focuser.Connected = True
    if not focuser.Connected:
        raise RuntimeError(f"Could not connect to ASCOM focuser: {ascom_id}")
    return focuser


def check_not_busy(focuser) -> bool:
    try:
        return not focuser.IsMoving
    except Exception:
        return False


def read_temperature(focuser) -> float:
    try:
        temp = focuser.Temperature
    except Exception as exc:
        raise RuntimeError(f"Could not read temperature: {exc}") from exc
    if temp is None:
        raise RuntimeError("Focuser returned None for Temperature — check EAF sensor.")
    return float(temp)


def read_position(focuser) -> int:
    return int(focuser.Position)


def move_focuser(focuser, target: int, timeout_s: float) -> int:
    focuser.Move(target)
    deadline = time.monotonic() + timeout_s
    while focuser.IsMoving:
        if time.monotonic() > deadline:
            raise TimeoutError(f"Focuser did not reach position {target} within {timeout_s:.0f} s.")
        time.sleep(MOVE_POLL_INTERVAL_S)
    return int(focuser.Position)


def move_focuser_with_backlash(
    focuser, target: int, current_position: int, backlash_steps: int, timeout_s: float
) -> int:
    if backlash_steps > 0 and target < current_position:
        overshoot = max(target - backlash_steps, 0)
        move_focuser(focuser, overshoot, timeout_s)
    return move_focuser(focuser, target, timeout_s)


def save_state(state: dict, state_json_path: Path) -> None:
    with state_json_path.open("w", encoding="utf-8") as handle:
        json.dump(state, handle, indent=2, ensure_ascii=False)
        handle.write("\n")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    log = setup_logging()
    args = parse_arguments()

    # --- Load state ---
    try:
        state_json_path = resolve_state_json(args.state_json)
        state = load_state(state_json_path)
    except (FileNotFoundError, ValueError) as exc:
        log.error(str(exc))
        log.info("END   | pos=N/A | reason=error")
        sys.exit(1)

    focus_ref       = int(state["focus_ref"])
    temp_ref        = float(state["temp_ref"])
    tcf             = float(state["model_tcf"])
    timestamp_ref   = state.get("timestamp_ref", "unknown")
    last_focus      = state.get("last_focus_applied", "unknown")
    last_t          = state.get("last_temp_applied", "unknown")

    last_t_str  = f"{last_t:.2f}{DEG_C}" if isinstance(last_t, float) else str(last_t)

    log.info(
        f"START | ref={timestamp_ref} | focus_ref={focus_ref} | "
        f"T_ref={temp_ref:.2f}{DEG_C} | TCF={tcf:.2f} | "
        f"last_focus={last_focus} | last_T={last_t_str} | "
        f"backlash={args.backlash} | min_correction={args.min_correction}"
        + (" | DRY_RUN" if args.dry_run else "")
    )

    # --- Connect ---
    focuser = None
    try:
        focuser = connect_focuser(args.ascom_id)
    except Exception as exc:
        log.error(f"ASCOM connection failed: {exc}")
        log.info("END   | pos=N/A | reason=error")
        sys.exit(1)

    # --- Busy check ---
    if not check_not_busy(focuser):
        current_position = read_position(focuser)
        log.warning("Focuser busy (IsMoving=True) — skipping this cycle, retry in 7 min")
        log.info(f"END   | pos={current_position} | reason=busy")
        focuser.Connected = False
        return

    current_position = read_position(focuser)

    # --- Temperature ---
    try:
        t_current = args.temp if args.temp is not None else read_temperature(focuser)
    except RuntimeError as exc:
        log.error(str(exc))
        log.info(f"END   | pos={current_position} | reason=error")
        focuser.Connected = False
        sys.exit(1)

    # --- Calculate correction ---
    delta_t      = t_current - temp_ref
    focus_target = round(focus_ref + tcf * delta_t)
    correction   = focus_target - current_position
    needs_backlash = args.backlash > 0 and focus_target < current_position

    # --- No correction needed ---
    if correction == 0:
        log.info(
            f"T={t_current:.2f}{DEG_C} | \u0394T={delta_t:+.2f}{DEG_C} | TCF={tcf:.2f} | "
            f"pos={current_position} | correction=0 | backlash=False | final={current_position} | no move needed"
        )
        log.info(f"END   | pos={current_position} | reason=ok")
        focuser.Connected = False
        return

    # --- Below min-correction threshold (backlash direction only) ---
    if needs_backlash and abs(correction) < args.min_correction:
        log.warning(
            f"T={t_current:.2f}{DEG_C} | \u0394T={delta_t:+.2f}{DEG_C} | TCF={tcf:.2f} | "
            f"pos={current_position} | correction={correction:+d} | "
            f"below min_correction={args.min_correction} (backlash direction) — skipped"
        )
        log.info(f"END   | pos={current_position} | reason=min_correction")
        focuser.Connected = False
        return

    # --- Dry run ---
    if args.dry_run:
        log.info(
            f"DRY | T={t_current:.2f}{DEG_C} | \u0394T={delta_t:+.2f}{DEG_C} | TCF={tcf:.2f} | "
            f"pos={current_position} | correction={correction:+d} | "
            f"backlash={needs_backlash} | target={focus_target} | move NOT executed"
        )
        log.info(f"END   | pos={current_position} | reason=dry_run")
        focuser.Connected = False
        return

    # --- Apply correction ---
    try:
        final_position = move_focuser_with_backlash(
            focuser, focus_target, current_position, args.backlash, args.move_timeout
        )
    except (TimeoutError, Exception) as exc:
        log.error(
            f"T={t_current:.2f}{DEG_C} | pos={current_position} | "
            f"target={focus_target} | move failed: {exc}"
        )
        log.info(f"END   | pos={current_position} | reason=error")
        focuser.Connected = False
        sys.exit(1)

    if abs(final_position - focus_target) > 5:
        log.warning(
            f"T={t_current:.2f}{DEG_C} | \u0394T={delta_t:+.2f}{DEG_C} | TCF={tcf:.2f} | "
            f"pos={current_position} | correction={correction:+d} | backlash={needs_backlash} | "
            f"final={final_position} | WARNING: differs from target {focus_target} by more than 5 steps"
        )
        log.info(f"END   | pos={final_position} | reason=ok_with_warning")
    else:
        log.info(
            f"T={t_current:.2f}{DEG_C} | \u0394T={delta_t:+.2f}{DEG_C} | TCF={tcf:.2f} | "
            f"pos={current_position} | correction={correction:+d} | "
            f"backlash={needs_backlash} | final={final_position}"
        )
        log.info(f"END   | pos={final_position} | reason=ok")

    state["last_temp_applied"]  = round(t_current, 2)
    state["last_focus_applied"] = focus_target
    save_state(state, state_json_path)

    focuser.Connected = False


if __name__ == "__main__":
    main()
