#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: 2026 David González López-Tercero <davidglt@dragonit.es>
# SPDX-License-Identifier: GPL-3.0-or-later

r"""
SharpCap Focus Sequencer — On-demand thermal focus compensator.

Reads the regression model and last autofocus reference produced by
sharpcap-focus-temperature (sharpcap_focus_state.json), queries the
current temperature from the ZWO EAF external sensor via ASCOM, and
moves the focuser to the thermally compensated position.

Formula
-------
    focus_target = focus_ref + TCF * (T_current - T_ref)

Where:
    focus_ref  = focuser position at the reference autofocus point
    T_ref      = temperature at the reference autofocus point
    T_current  = current temperature read from the EAF sensor
    TCF        = temperature compensation factor (steps / °C)

Backlash compensation
---------------------
    To eliminate backlash, the focuser always arrives at the target
    from below (increasing step numbers = outward direction on C8 + F/6.3).
    If the target is below the current position, the script first moves
    to (target - backlash_steps) and then moves up to the target.
    The backlash value is configurable via --backlash (default: 500 steps).
    Set to 0 to disable backlash compensation entirely.

Minimum correction threshold
-----------------------------
    The script skips the move if the absolute correction is smaller than
    --min-correction (default: 20 steps). This avoids unnecessary motor
    activity and backlash overshoot cycles when the thermal drift is
    negligible. With TCF = -61.59 steps/°C, 20 steps corresponds to
    ~0.32 °C of temperature change.
    Set to 0 to always move regardless of correction size.

Busy detection
--------------
    If the focuser is already moving when the script connects (e.g. SharpCap
    is running an autofocus), the script aborts immediately and exits cleanly.
    The PERIODIC ThermalCorrection will retry in 7 minutes.

ASCOM access
------------
    ASCOM Device Hub is required to allow simultaneous access from
    SharpCap and this script. Configure Device Hub to proxy
    ASCOM.EAF_2.Focuser (main tube: C8 + ASI2600MC Pro, ~25 000 steps)
    and point both clients to ASCOM.DeviceHub.Focuser.

    Direct ProgIDs (ZWO EAF driver, single-client only):
        ASCOM.EAF.Focuser    -> first EAF  (guide tube: 50ED + ASI224MC,  ~335 000 steps)
        ASCOM.EAF_2.Focuser  -> second EAF (main tube:  C8  + ASI2600MC Pro, ~25 000 steps)

State JSON lookup
-----------------
    The script looks for sharpcap_focus_state.json in this order:
        1. Path supplied via --state-json (if given)
        2. Same directory as this script
        3. Sibling repository: ..\sharpcap-focus-temperature\

    The state JSON is generated by sharpcap-focus-temperature and must
    NOT be copied into this repository; always use the original output
    from the producer repository (single source of truth).

Usage
-----
    python focus_sequencer.py
    python focus_sequencer.py --state-json path/to/sharpcap_focus_state.json
    python focus_sequencer.py --ascom-id "ASCOM.EAF_2.Focuser"
    python focus_sequencer.py --dry-run
    python focus_sequencer.py --dry-run --temp 18.5
    python focus_sequencer.py --backlash 500
    python focus_sequencer.py --backlash 0        # disable backlash compensation
    python focus_sequencer.py --min-correction 20 # skip moves smaller than 20 steps
    python focus_sequencer.py --min-correction 0  # always move

Author
------
David González López-Tercero

Contact
-------
Email: davidglt@dragonit.es
Website: https://dragonit.es

Date
----
2026-08-25

License
-------
GPL-3.0-or-later
"""

import argparse
import json
import sys
import time
from pathlib import Path

DEG_C = "\u00B0C"
STATE_JSON_FILENAME = "sharpcap_focus_state.json"
# Route through ASCOM Device Hub so SharpCap and this script can connect simultaneously.
# Device Hub must be configured to proxy ASCOM.EAF_2.Focuser (C8 + ASI2600MC Pro).
DEFAULT_ASCOM_ID = "ASCOM.DeviceHub.Focuser"
DEFAULT_BACKLASH_STEPS = 500
DEFAULT_MIN_CORRECTION = 20
MOVE_TIMEOUT_S = 60
MOVE_POLL_INTERVAL_S = 0.5

# Candidate paths for state JSON auto-detection (evaluated in order when --state-json
# is not supplied). Paths are relative to this script's own directory.
_STATE_JSON_CANDIDATES = [
    Path(__file__).resolve().parent / STATE_JSON_FILENAME,
    Path(__file__).resolve().parent.parent / "sharpcap-focus-temperature" / STATE_JSON_FILENAME,
]


def resolve_state_json(cli_path: str | None) -> Path:
    """Return the resolved path to sharpcap_focus_state.json.

    If *cli_path* is provided, use it directly (and raise if absent).
    Otherwise try each candidate in _STATE_JSON_CANDIDATES and return the
    first one that exists.  Raises FileNotFoundError if none is found.
    """
    if cli_path is not None:
        p = Path(cli_path).resolve()
        if not p.exists():
            raise FileNotFoundError(
                f"--state-json path not found: {p}"
            )
        return p

    for candidate in _STATE_JSON_CANDIDATES:
        if candidate.exists():
            return candidate

    searched = "\n  ".join(str(c) for c in _STATE_JSON_CANDIDATES)
    raise FileNotFoundError(
        f"sharpcap_focus_state.json not found in any of:\n  {searched}\n"
        "Run sharpcap_focuser.py (sharpcap-focus-temperature) first to generate it."
    )


def parse_arguments():
    """Parse and return command-line arguments."""
    parser = argparse.ArgumentParser(
        description=(
            "On-demand thermal focus compensator for ZWO EAF via ASCOM. "
            "Reads the model from sharpcap_focus_state.json and moves the "
            "focuser to the thermally corrected position."
        )
    )
    parser.add_argument(
        "--state-json",
        default=None,
        help=(
            "Path to sharpcap_focus_state.json produced by "
            "sharpcap-focus-temperature. If omitted, the script searches "
            "the local directory and then the sibling repository "
            "sharpcap-focus-temperature automatically."
        ),
    )
    parser.add_argument(
        "--ascom-id",
        default=DEFAULT_ASCOM_ID,
        help=f"ASCOM ProgID of the focuser driver. Default: {DEFAULT_ASCOM_ID}",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help=(
            "Calculate and print the target position without moving the "
            "focuser or writing the state JSON."
        ),
    )
    parser.add_argument(
        "--temp",
        type=float,
        default=None,
        metavar="DEGREES",
        help=(
            f"Current temperature in {DEG_C} for --dry-run simulation. "
            "If omitted in dry-run mode, the script prompts interactively."
        ),
    )
    parser.add_argument(
        "--backlash",
        type=int,
        default=DEFAULT_BACKLASH_STEPS,
        metavar="STEPS",
        help=(
            f"Backlash compensation in steps. The focuser always arrives at the "
            f"target from below (increasing direction). If the target is below "
            f"the current position, the script first moves to "
            f"(target - backlash) and then back up to the target. "
            f"Set to 0 to disable. Default: {DEFAULT_BACKLASH_STEPS}"
        ),
    )
    parser.add_argument(
        "--min-correction",
        type=int,
        default=DEFAULT_MIN_CORRECTION,
        metavar="STEPS",
        help=(
            f"Minimum absolute correction (in steps) required to trigger a move. "
            f"If the calculated correction is smaller than this value, the script "
            f"exits without moving the focuser. Avoids unnecessary motor activity "
            f"when thermal drift is negligible. "
            f"Set to 0 to always move. Default: {DEFAULT_MIN_CORRECTION}"
        ),
    )
    parser.add_argument(
        "--move-timeout",
        type=float,
        default=MOVE_TIMEOUT_S,
        help=f"Seconds to wait for each focuser move to complete. Default: {MOVE_TIMEOUT_S}",
    )
    return parser.parse_args()


def load_state(state_json_path: Path) -> dict:
    """Load and validate the focus state JSON."""
    with state_json_path.open("r", encoding="utf-8") as handle:
        state = json.load(handle)

    required = [
        "focus_ref",
        "temp_ref",
        "model_tcf",
        "last_temp_applied",
        "last_focus_applied",
    ]
    missing = [k for k in required if k not in state]
    if missing:
        raise ValueError(
            f"State JSON is missing required fields: {missing}\n"
            "Re-run sharpcap_focuser.py to regenerate it."
        )

    if state["model_tcf"] is None:
        raise ValueError(
            "model_tcf is null in the state JSON — not enough autofocus points "
            "to fit the regression model. Collect more sessions and re-run "
            "sharpcap_focuser.py."
        )

    return state


def connect_focuser(ascom_id: str):
    """Connect to the ASCOM focuser and return the COM object."""
    try:
        import win32com.client
    except ImportError:
        raise ImportError(
            "pywin32 is required to use ASCOM on Windows.\n"
            "Install it with: pip install pywin32"
        )

    focuser = win32com.client.Dispatch(ascom_id)
    focuser.Connected = True

    if not focuser.Connected:
        raise RuntimeError(f"Could not connect to ASCOM focuser: {ascom_id}")

    return focuser


def check_not_busy(focuser) -> bool:
    """Return True if the focuser is idle, False if it is already moving.

    Called immediately after connect so we can abort cleanly if SharpCap
    is running an autofocus or any other move at the same time.
    """
    try:
        return not focuser.IsMoving
    except Exception:
        # If IsMoving cannot be read, assume busy to be safe.
        return False


def read_temperature(focuser) -> float:
    """Read current temperature from the EAF external sensor via ASCOM."""
    try:
        temp = focuser.Temperature
    except Exception as exc:
        raise RuntimeError(
            f"Could not read temperature from focuser: {exc}\n"
            "Check that the ZWO EAF external sensor is connected."
        ) from exc

    if temp is None:
        raise RuntimeError(
            "Focuser returned None for Temperature. "
            "Check that the ZWO EAF external sensor is plugged in."
        )

    return float(temp)


def read_position(focuser) -> int:
    """Read current focuser position."""
    return int(focuser.Position)


def move_focuser(focuser, target: int, timeout_s: float) -> int:
    """Move focuser to target position and wait for completion."""
    focuser.Move(target)

    deadline = time.monotonic() + timeout_s
    while focuser.IsMoving:
        if time.monotonic() > deadline:
            raise TimeoutError(
                f"Focuser did not reach position {target} within "
                f"{timeout_s:.0f} s."
            )
        time.sleep(MOVE_POLL_INTERVAL_S)

    return int(focuser.Position)


def move_focuser_with_backlash(
    focuser, target: int, current_position: int, backlash_steps: int, timeout_s: float
) -> int:
    """Move focuser to target, always arriving from below to eliminate backlash.

    Strategy:
        - If target >= current_position: move directly (already approaching
          from below or staying put).
        - If target < current_position and backlash_steps > 0: first move to
          (target - backlash_steps), then move up to target. This ensures the
          final approach is always in the increasing (outward) direction.
        - If backlash_steps == 0: move directly regardless of direction.

    Returns the final focuser position after all moves.
    """
    if backlash_steps > 0 and target < current_position:
        overshoot = target - backlash_steps
        overshoot = max(overshoot, 0)  # clamp to valid range
        print(f"  Backlash overshoot   : moving to {overshoot} steps first...")
        move_focuser(focuser, overshoot, timeout_s)
        print(f"  Overshoot reached. Moving up to target {target} steps...")
    else:
        print(f"  Approaching target {target} steps directly (no overshoot needed)...")

    return move_focuser(focuser, target, timeout_s)


def save_state(state: dict, state_json_path: Path) -> None:
    """Write the updated state back to the JSON file."""
    with state_json_path.open("w", encoding="utf-8") as handle:
        json.dump(state, handle, indent=2, ensure_ascii=False)
        handle.write("\n")


def main():
    """Run the on-demand thermal focus compensation."""
    args = parse_arguments()

    # --- Resolve state JSON path ---
    state_json_path = resolve_state_json(args.state_json)
    print(f"Loading state from: {state_json_path}")
    state = load_state(state_json_path)

    focus_ref = int(state["focus_ref"])
    temp_ref = float(state["temp_ref"])
    tcf = float(state["model_tcf"])
    last_temp = float(state["last_temp_applied"])
    last_focus = int(state["last_focus_applied"])
    timestamp_ref = state.get("timestamp_ref", "unknown")

    print(f"Reference autofocus  : {timestamp_ref}")
    print(f"Reference position   : {focus_ref} steps @ {temp_ref:.2f} {DEG_C}")
    print(f"Last applied         : {last_focus} steps @ {last_temp:.2f} {DEG_C}")
    print(f"TCF                  : {tcf:.2f} steps/{DEG_C}")
    print(f"Backlash             : {args.backlash} steps")
    print(f"Min correction       : {args.min_correction} steps")

    # --- Connect and read temperature ---
    if args.dry_run:
        print("\n[DRY RUN] Skipping ASCOM connection.")
        if args.temp is not None:
            t_current = args.temp
            print(f"Temperature (--temp) : {t_current:.2f} {DEG_C}")
        else:
            print("Enter current temperature manually for simulation:")
            try:
                t_current = float(input(f"  Temperature ({DEG_C}): "))
            except (ValueError, EOFError):
                print("Invalid input. Use --temp <value> for non-interactive dry-run.")
                sys.exit(1)
        current_position = last_focus
    else:
        print(f"\nConnecting to ASCOM focuser: {args.ascom_id}")
        focuser = connect_focuser(args.ascom_id)
        print("Connected.")

        # Abort immediately if SharpCap or any other client is already moving
        # the focuser. The PERIODIC ThermalCorrection will retry in 7 minutes.
        if not check_not_busy(focuser):
            print("Focuser is busy (IsMoving=True). Skipping this cycle — will retry in 7 min.")
            focuser.Connected = False
            print("\nDone.")
            return

        t_current = read_temperature(focuser)
        current_position = read_position(focuser)
        print(f"Current temperature  : {t_current:.2f} {DEG_C}")
        print(f"Current position     : {current_position} steps")

    # --- Calculate correction ---
    delta_t = t_current - temp_ref
    delta_steps = tcf * delta_t
    focus_target = round(focus_ref + delta_steps)
    correction = focus_target - current_position

    print(f"\nDelta T (current - ref) : {delta_t:+.2f} {DEG_C}")
    print(f"Delta steps (TCF * dT)  : {delta_steps:+.1f}")
    print(f"Target position         : {focus_target} steps")
    print(f"Correction needed       : {correction:+d} steps")

    # --- Check minimum correction threshold ---
    if abs(correction) < args.min_correction:
        print(
            f"\nCorrection ({abs(correction)} steps) is below "
            f"--min-correction ({args.min_correction} steps). "
            "No move needed."
        )
        if not args.dry_run:
            focuser.Connected = False
        print("\nDone.")
        return

    # --- Apply or report ---
    if args.dry_run:
        if args.backlash > 0 and focus_target < current_position:
            overshoot = max(focus_target - args.backlash, 0)
            print(
                f"\n[DRY RUN] Would overshoot to {overshoot} steps, "
                f"then move up to {focus_target} steps."
            )
        else:
            print(f"\n[DRY RUN] Would move directly to {focus_target} steps.")
        print("[DRY RUN] Move NOT executed.")
    else:
        print(f"\nMoving focuser to {focus_target} steps...")
        final_position = move_focuser_with_backlash(
            focuser, focus_target, current_position, args.backlash, args.move_timeout
        )
        print(f"Move complete. Final position: {final_position} steps")

        if abs(final_position - focus_target) > 5:
            print(
                f"WARNING: Final position {final_position} differs from "
                f"target {focus_target} by more than 5 steps."
            )

        # Update state JSON with current values
        state["last_temp_applied"] = round(t_current, 2)
        state["last_focus_applied"] = focus_target
        save_state(state, state_json_path)
        print(f"State JSON updated: {state_json_path}")

        focuser.Connected = False

    print("\nDone.")


if __name__ == "__main__":
    main()
